pipeline:
  identifier: Build_newbot419_new_1738613669883
  name: Build new
  orgIdentifier: default
  projectIdentifier: king
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1738613638538
        repoName: newbot419/new
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: git clone https://github.com/newbot419/new.git
              - step:
                  type: Run
                  name: Run_4
                  identifier: Run_4
                  spec:
                    shell: Sh
                    command: cd new
              - step:
                  type: Run
                  name: Run_5
                  identifier: Run_5
                  spec:
                    shell: Sh
                    command: gcc king.c -o king -lpthread
              - step:
                  type: Run
                  name: Run_6
                  identifier: Run_6
                  spec:
                    shell: Sh
                    command: python3 king.py
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
